BROKER_URL: 108.142.139.160
BROKER_PORT: 8083
CA_CERT: /home/keila/smartoceanplatform/root/keystores/broker.chain.pem
TOPIC: ${TOPIC}
QOS: ${QOS}
NR_OF_MESSAGES: 3
TLS_ENABLED: True
CLEAN_START: True
RETAIN: False
REATTEMPTS: 0
KEEPALIVE: 60
TESTDATA_PATH: /home/keila/smartoceanplatform/mqtt_benchmark/publisher/data/provider1