BROKER_URL: 0.0.0.0
BROKER_PORT: 8083
TOPIC: ${TOPIC}
QOS: ${QOS}
NR_OF_MESSAGES: 3
PUBLISH_INTERVAL: 1
TLS_ENABLED: False
CLEAN_START: True
RETAIN: False
REATTEMPTS: 0
KEEPALIVE: 60
TESTDATA_PATH: /home/keila/smartoceanplatform/mqtt_benchmark/publisher/data/provider1