# BROKER_URL: a5aea22f69fb49e9a24b4981057181a6.s2.eu.hivemq.cloud
# BROKER_PORT: 8883
# TOPIC: broker/evaluation/topic
# QOS: 0
# NR_OF_MESSAGES: 1000
# PUBLISH_INTERVAL: 1
# TLS_ENABLED: False
# REATTEMPTS: -1
# CLEAN_START: False
# KEEPALIVE: False
# SESSION_EXPIRY_INTERVAL: 3600
# RETAIN: False
# REATTEMPT_MIN_DELAY: 2
# REATTEMPT_MAX_DELAY: 30
# TESTDATA_PATH: ""

BROKER_URL: broker # 956d8d961c3c4af4ac704e372f13955b.s1.eu.hivemq.cloud
BROKER_PORT: 1883 #8883
TOPIC:  site1/#
QOS: 0
NR_OF_MESSAGES: 1000
PUBLISH_INTERVAL: 5
CLEAN_START: True
SESSION_EXPIRY_INTERVAL: 0
TLS_ENABLED: False #True #False #True
REATTEMPTS: -1
#CA_CERT: ../mqtt_benchmark/certs/server.pem
TESTDATA_PATH: testdata/aadi
CLIENT_ID: subscriber