BROKER_URL: a5aea22f69fb49e9a24b4981057181a6.s2.eu.hivemq.cloud
BROKER_PORT: 8883
TOPIC: smartocean/pilotdemo_0001/austevoll/wsense/node1
QOS: 2
NR_OF_MESSAGES: 3
PUBLISH_INTERVAL: 5
TLS_ENABLED: True
TESTDATA_PATH: testdata/wsense/valid_data