BROKER_URL: a5aea22f69fb49e9a24b4981057181a6.s2.eu.hivemq.cloud
BROKER_PORT: 8883
TOPIC: smartocean/testing/virtualsensorhub
QOS: 2
NR_OF_MESSAGES: 3
PUBLISH_SLEEP_TIME: 5
TLS_ENABLED: True
DESCRIPTION: HVL Virtual Sensor Hub Timeseries
TIMESERIES: HVL:VTS:0001
SOURCE: HVL Virtual Sensor Hub
SOURCE_ID: HVL:0001
LOCATION_LATITUDE: 60.3692257067
LOCATION_LONGITUDE: 5.3505234505
FORMAT: SMARTOCEAN_V1